### PR TITLE
Update Dockerfile - add send2trash pip package

### LINKED ISSUE #20: Delete archive after extraction & Don't extract the following files (folders?)
First of all: thank you for your much appreciated work!

The automated deletion of packaged archives after extraction apparently does not currently work with this Docker.
funktion: **“Delete archive after extraction:”** (ExtractArchive --> Send2Trash lib not found)

It is also currently not possible to exclude certain folders contained in archives when extracting, for example "sample-folder". This works well for files, by the way.
funktion: **"Don't extract the following files:"**

UnRar would have to be replaced by p7zip p7zip-full p7zip-rar.

Would it be possible to include these important functions in one of the next updates?

### PR DESCRIPTION
**Pull request by zach-morris**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-pyload/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add [send2trash](https://pypi.org/project/Send2Trash/) into pip install list.  Without it pyload throws the error:
```
Send2Trash lib not found
```
After extracting an archive.

## Benefits of this PR and context:

Adding the pip package will remove the error.  Fixes #20 

## How Has This Been Tested?

Tested locally

## Source / References:

https://discourse.linuxserver.io/t/pyload-send2trash-lib-not-found/2431

### CODE REVIEW

**Comment by zach-morris** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Well, the PR needs to be merged.  How do you go about getting linuxserver.ios attention to do that?

**Comment by zach-morris** [comment]
Pinging @aptalca , @technorabilia, @zetneteork as I see those people have the ability to make commits

**Review by zetneteork — COMMENTED** [review]
It would be nice to keep the alignment.

**Comment by zach-morris** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

¯\_(ツ)_/¯. oh well.  i tried

**Comment by aptalca** [comment]
Please add it to all arches, in alphabetical order, and add a changelog entry. Thanks

**Pull request closed without merging**
